proxy:
  https:
    enabled: true
    hosts:
      - try.openbiosim.org
    letsencrypt:
      contactEmail: XXXXXXXXXXXXXXXXXXX
singleuser:
  image:
    name: openbiosim/notebook
    tag: 2024.1.0
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 600
          cull_interval: 120
          cull_connected: true
          cull_busy: false
  storage:
    type: none
  memory:
    limit: 4.0G
    guarantee: 0.5G
  cpu:
    limit: 1.0
    guarantee: 0.25
prePuller:
  continuous:
    enabled: true
cull:
  enabled: true
  users: true
  removeNamedServers: true
  timeout: 600
  every: 120
hub:
  config:
    JupyterHub:
      admin_access: false
    Authenticator:
      auto_login: true
    GitHubOAuthenticator:
      client_id: XXXXXXXXXX
      client_secret: XXXXXXXXXXXXXX
      oauth_callback_url: https://try.openbiosim.org/hub/oauth_callback
      allow_all: true
      block_users:
        - XXXXXX
    JupyterHub:
      authenticator_class: github

