proxy:
  https:
    enabled: true
    hosts:
      - try.siremol.org
    letsencrypt:
      contactEmail: chryswoods@openbiosim.org
singleuser:
  image:
    name: openbiosim/notebook
    tag: latest
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 600
          cull_interval: 120
          cull_connected: true
          cull_busy: false
  storage:
    type: none
  memory:
    limit: 2.0G
    guarantee: 0.5G
  cpu:
    limit: 1.0
    guarantee: 0.2
prePuller:
  continuous:
    enabled: true
cull:
  enabled: true
  users: true
  removeNamedServers: true
  timeout: 600
  every: 120
hub:
  config:
    JupyterHub:
      admin_access: false
    Authenticator:
      auto_login: true
    GitHubOAuthenticator:
      client_id: {CHANGE ME}
      client_secret: {CHANGE ME}
      oauth_callback_url: https://try.siremol.org/hub/oauth_callback
    JupyterHub:
      authenticator_class: github
